name: comida_appflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0
  google_fonts: ^6.2.1
  http: ^1.2.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/fondo.jpg